name: voicenotes
description: "A Flutter project for voice notes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#c988be"
  image: assets/images/company_logo.png
  fullscreen: true
  android_gravity: fill 
  ios_content_mode: scaleAspectFill
  web: false

  android_12:
    color: "#c988be"
    image: assets/images/company_logo.png
    fullscreen: true
    android_gravity: fill
    ios_content_mode: scaleAspectFill

  
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.3.0
  font_awesome_flutter: ^10.8.0
  splash_master: ^0.0.2
  
  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
    
  # Database - Updated to compatible versions
  drift: ^2.26.0
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.5
  path: ^1.8.3
  ffi: ^2.1.0
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # Audio
  just_audio: ^0.9.46  # For audio playback
  record: ^5.0.1       # For audio recording
  audio_session: ^0.1.25
  
  # Authentication
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  flutter_login_facebook: ^2.0.1
  cloud_firestore: ^5.6.6
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.2.2
  share_plus: ^10.1.4
  url_launcher: ^6.2.2
  logger: ^2.0.2
  package_info_plus: ^8.3.0
  http_parser: ^4.1.2
  flutter_hooks: ^0.21.2
  permission_handler: ^11.0.0
  
  # Exporting
  pdf: ^3.11.3
  printing: ^5.14.2
  docx_template: ^0.4.0

  # Routing
  go_router: ^14.8.1

  #Subscription
  in_app_purchase: ^3.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  analyzer: ^7.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/templates/
    - assets/fonts/
    