name: voicenotes
description: "A Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  
  # Local Storage
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # Audio
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  audio_session: ^0.1.18
  
  # Authentication
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  logger: ^2.0.2+1

  # Routing

  go_router: ^14.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

 